const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt){const r=await fetch(url,opt);const j=await r.json();if(!r.ok)throw new Error(j.error||'Erreur');return j}
async function load(){const [s,students,p,b]=await Promise.all([api('/api/admin/stats'),api('/api/admin/students'),api('/api/admin/programs'),api('/api/admin/buttons')]);$('#stats').innerHTML=`<div class=stat><b>${s.students}</b>Étudiants</div><div class=stat><b>${s.programs}</b>Formations</div><div class=stat><b>${s.pending}</b>En attente</div><div class=stat><b>${Number(s.revenue).toLocaleString()}</b> HTG confirmés</div>`;$('#students').innerHTML=students.length? students.map(x=>`<tr><td>${esc(x.student_no)}</td><td>${esc(x.name)}</td><td>${esc(x.program_name||'—')}</td><td>${esc(x.phone)}</td><td>${esc(x.status)}</td></tr>`).join(''):'';$('#programs').innerHTML=p.map(x=>`<div class=item><span><b>${esc(x.name)}</b> — ${esc(x.duration)} — ${Number(x.price_htg).toLocaleString()} HTG<br><small>${esc(x.description)}</small></span></div>`).join('');$('#buttons').innerHTML=b.map(x=>`<div class=item><span><b>${esc(x.label)}</b> → ${esc(x.url)}<br><small>${esc(x.description)}</small></span><button class=danger onclick="delButton(${x.id})">Supprimer</button></div>`).join('')}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#login').hidden=true;$('#app').hidden=false;load()}catch(err){$('#loginMsg').textContent=err.message}});
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
$('#programForm').addEventListener('submit',async e=>{e.preventDefault();await api('/api/admin/programs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();load()});
$('#buttonForm').addEventListener('submit',async e=>{e.preventDefault();await api('/api/admin/buttons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();load()});
async function delButton(id){if(confirm('Supprimer ce bouton ?')){await api('/api/admin/buttons/'+id,{method:'DELETE'});load()}}
api('/api/admin/me').then(()=>{$('#login').hidden=true;$('#app').hidden=false;load()}).catch(()=>{});
