require('dotenv').config();
const express=require('express'),cookieParser=require('cookie-parser'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3'),path=require('path'),fs=require('fs');
const app=express(),PORT=process.env.PORT||10000,DATA_DIR=process.env.DATA_DIR||__dirname,SECRET=process.env.JWT_SECRET||'CHANGE_ME_CETEP';
fs.mkdirSync(DATA_DIR,{recursive:true}); app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true}));app.use(cookieParser());
const db=new Database(path.join(DATA_DIR,'cetep.sqlite'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password_hash TEXT);CREATE TABLE IF NOT EXISTS programs(id INTEGER PRIMARY KEY,name TEXT NOT NULL,duration TEXT,description TEXT,price_htg REAL DEFAULT 0,active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY,student_no TEXT UNIQUE NOT NULL,name TEXT NOT NULL,birth_date TEXT,birth_place TEXT,phone TEXT,email TEXT,program_id INTEGER,education TEXT,blood_group TEXT,responsible_person TEXT,marital_status TEXT,status TEXT DEFAULT 'En attente',password_hash TEXT,access_enabled INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(program_id) REFERENCES programs(id) ON DELETE SET NULL);CREATE TABLE IF NOT EXISTS teachers(id INTEGER PRIMARY KEY,teacher_no TEXT UNIQUE,name TEXT NOT NULL,email TEXT UNIQUE,phone TEXT,password_hash TEXT,active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS modules(id INTEGER PRIMARY KEY,program_id INTEGER,title TEXT NOT NULL,description TEXT,order_no INTEGER DEFAULT 1,active INTEGER DEFAULT 1,FOREIGN KEY(program_id) REFERENCES programs(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS lessons(id INTEGER PRIMARY KEY,module_id INTEGER,title TEXT NOT NULL,type TEXT DEFAULT 'Texte',content TEXT,video_url TEXT,file_url TEXT,order_no INTEGER DEFAULT 1,active INTEGER DEFAULT 1,FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,student_id INTEGER,amount_htg REAL NOT NULL,method TEXT,status TEXT DEFAULT 'Confirmé',reference TEXT UNIQUE,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE SET NULL);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '');`);
const defaults={school_name:'CETEP',school_full_name:"Centre d'Encadrement Technique et Professionnel",slogan:'Formation • Orientation • Insertion professionnelle',primary_color:'#0d2b52',secondary_color:'#1677b8',accent_color:'#087443',logo_text:'CETEP',logo_url:''};const set=db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)');for(const [k,v] of Object.entries(defaults))set.run(k,v);
const adminEmail=process.env.ADMIN_EMAIL||'admin@cetep.ht',adminPass=process.env.ADMIN_PASSWORD||'CHANGEZ_MOI';if(!db.prepare('SELECT 1 FROM admins LIMIT 1').get())db.prepare('INSERT INTO admins(email,password_hash) VALUES(?,?)').run(adminEmail,bcrypt.hashSync(adminPass,12));
if(db.prepare('SELECT COUNT(*) c FROM programs').get().c===0){const q=db.prepare('INSERT INTO programs(name,duration,description,price_htg) VALUES(?,?,?,?)');q.run('Secourisme de base','9 mois','Formation aux premiers secours et à la sécurité.',0);q.run('Aide-soignant(e)','6 mois','Formation orientée vers les soins de base.',0);q.run('Électricité bâtiment','6 mois','Installation et maintenance électrique.',0);q.run('Plomberie','6 mois','Installation et entretien des réseaux de plomberie.',0);q.run('Sérigraphie','6 mois','Techniques professionnelles de sérigraphie.',0);}
function auth(req,res,next){try{const t=req.cookies.cetep_token;if(!t)throw 0;req.user=jwt.verify(t,SECRET);next()}catch{res.status(401).json({error:'Non autorisé'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Accès interdit'});next()}
function settings(){return Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]))}
function studentNo(){let n=db.prepare('SELECT COUNT(*) c FROM students').get().c+1;let x=`CETEP-${new Date().getFullYear()}-${String(n).padStart(4,'0')}`;while(db.prepare('SELECT 1 FROM students WHERE student_no=?').get(x)){n++;x=`CETEP-${new Date().getFullYear()}-${String(n).padStart(4,'0')}`}return x}
app.use(express.static(__dirname));
app.get('/health',(req,res)=>res.json({ok:true,service:'CETEP',version:'9.0.0'}));
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));app.get('/login',(req,res)=>res.sendFile(path.join(__dirname,'login.html')));
app.post('/api/login',(req,res)=>{const a=db.prepare('SELECT * FROM admins WHERE email=?').get(req.body?.email||'');if(!a||!bcrypt.compareSync(req.body?.password||'',a.password_hash))return res.status(401).json({error:'Identifiants invalides'});res.cookie('cetep_token',jwt.sign({id:a.id,email:a.email,role:'admin'},SECRET,{expiresIn:'8h'}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000});res.json({ok:true})});
app.post('/api/logout',(req,res)=>{res.clearCookie('cetep_token');res.json({ok:true})});
app.get('/api/public/settings',(req,res)=>res.json(settings()));app.get('/api/public/programs',(req,res)=>res.json(db.prepare('SELECT * FROM programs WHERE active=1 ORDER BY id').all()));
app.post('/api/admissions',(req,res)=>{try{const b=req.body||{};if(!b.name||!b.phone||!b.program_id)return res.status(400).json({error:'Nom, téléphone et formation obligatoires.'});const no=studentNo();db.prepare('INSERT INTO students(student_no,name,birth_date,phone,email,program_id,education) VALUES(?,?,?,?,?,?,?)').run(no,b.name,b.birth_date||null,b.phone,b.email||null,Number(b.program_id),b.education||null);res.json({ok:true,student_no:no})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/admin/stats',auth,admin,(req,res)=>res.json({students:db.prepare('SELECT COUNT(*) c FROM students').get().c,teachers:db.prepare('SELECT COUNT(*) c FROM teachers').get().c,programs:db.prepare('SELECT COUNT(*) c FROM programs WHERE active=1').get().c,pending:db.prepare("SELECT COUNT(*) c FROM students WHERE status='En attente'").get().c,revenue:db.prepare("SELECT COALESCE(SUM(amount_htg),0) s FROM payments WHERE status='Confirmé'").get().s}));
app.get('/api/admin/settings',auth,admin,(req,res)=>res.json(settings()));
app.post('/api/admin/logo/reset',auth,admin,(req,res)=>{db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('logo_url','');res.json({ok:true,settings:settings()})});app.put('/api/admin/settings',auth,admin,(req,res)=>{const q=db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');for(const k of Object.keys(defaults))if(req.body[k]!==undefined)q.run(k,String(req.body[k]));res.json({ok:true,settings:settings()})});
app.get('/api/admin/students',auth,admin,(req,res)=>res.json(db.prepare('SELECT s.*,p.name program_name FROM students s LEFT JOIN programs p ON p.id=s.program_id ORDER BY s.id DESC').all()));
app.post('/api/admin/students',auth,admin,(req,res)=>{try{const b=req.body||{};if(!b.name||!b.phone||!b.program_id)return res.status(400).json({error:'Nom, téléphone et formation sont obligatoires.'});const no=studentNo(),pw=String(b.password||'123456');if(pw.length<6)return res.status(400).json({error:'Mot de passe: 6 caractères minimum.'});const r=db.prepare(`INSERT INTO students(student_no,name,birth_date,birth_place,phone,email,program_id,education,blood_group,responsible_person,marital_status,status,password_hash,access_enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(no,b.name,b.birth_date||null,b.birth_place||null,b.phone,b.email||null,Number(b.program_id),b.education||null,b.blood_group||null,b.responsible_person||null,b.marital_status||null,b.status||'Actif',bcrypt.hashSync(pw,12),b.access_enabled?1:0);res.json({ok:true,id:r.lastInsertRowid,student_no:no})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/admin/students/:id',auth,admin,(req,res)=>{const b=req.body||{};db.prepare(`UPDATE students SET name=?,birth_date=?,birth_place=?,phone=?,email=?,program_id=?,education=?,blood_group=?,responsible_person=?,marital_status=?,status=? WHERE id=?`).run(b.name,b.birth_date||null,b.birth_place||null,b.phone,b.email||null,b.program_id?Number(b.program_id):null,b.education||null,b.blood_group||null,b.responsible_person||null,b.marital_status||null,b.status||'En attente',req.params.id);res.json({ok:true})});
app.post('/api/admin/students/:id/access',auth,admin,(req,res)=>{const s=db.prepare('SELECT * FROM students WHERE id=?').get(req.params.id);if(!s)return res.status(404).json({error:'Étudiant introuvable'});let hash=s.password_hash;if(req.body.password)hash=bcrypt.hashSync(req.body.password,12);db.prepare('UPDATE students SET access_enabled=?,status=?,password_hash=? WHERE id=?').run(req.body.enabled?1:0,req.body.enabled?'Actif':'Suspendu',hash,s.id);res.json({ok:true})});
app.get('/api/admin/teachers',auth,admin,(req,res)=>res.json(db.prepare('SELECT id,teacher_no,name,email,phone,active FROM teachers ORDER BY id DESC').all()));app.post('/api/admin/teachers',auth,admin,(req,res)=>{try{const b=req.body;const no=`PROF-${new Date().getFullYear()}-${String(db.prepare('SELECT COUNT(*) c FROM teachers').get().c+1).padStart(4,'0')}`;const r=db.prepare('INSERT INTO teachers(teacher_no,name,email,phone,password_hash) VALUES(?,?,?,?,?)').run(no,b.name,b.email,b.phone||'',bcrypt.hashSync(b.password||'123456',12));res.json({ok:true,id:r.lastInsertRowid,teacher_no:no})}catch(e){res.status(400).json({error:e.message})}});app.post('/api/admin/teachers/:id/status',auth,admin,(req,res)=>{db.prepare('UPDATE teachers SET active=? WHERE id=?').run(req.body.active?1:0,req.params.id);res.json({ok:true})});
app.get('/api/admin/programs',auth,admin,(req,res)=>res.json(db.prepare('SELECT * FROM programs ORDER BY id').all()));app.post('/api/admin/programs',auth,admin,(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO programs(name,duration,description,price_htg,active) VALUES(?,?,?,?,?)').run(b.name,b.duration||'',b.description||'',Number(b.price_htg||0),b.active==='false'?0:1);res.json({ok:true,id:r.lastInsertRowid})});app.put('/api/admin/programs/:id',auth,admin,(req,res)=>{const b=req.body;db.prepare('UPDATE programs SET name=?,duration=?,description=?,price_htg=?,active=? WHERE id=?').run(b.name,b.duration||'',b.description||'',Number(b.price_htg||0),b.active==='false'?0:1,req.params.id);res.json({ok:true})});app.delete('/api/admin/programs/:id',auth,admin,(req,res)=>{db.prepare('DELETE FROM programs WHERE id=?').run(req.params.id);res.json({ok:true})});
app.get('/api/admin/modules',auth,admin,(req,res)=>res.json(db.prepare('SELECT m.*,p.name program_name FROM modules m JOIN programs p ON p.id=m.program_id ORDER BY p.id,m.order_no').all()));app.post('/api/admin/modules',auth,admin,(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO modules(program_id,title,description,order_no) VALUES(?,?,?,?)').run(Number(b.program_id),b.title,b.description||'',Number(b.order_no||1));res.json({ok:true,id:r.lastInsertRowid})});app.get('/api/admin/lessons',auth,admin,(req,res)=>res.json(db.prepare('SELECT l.*,m.title module_title,p.name program_name FROM lessons l JOIN modules m ON m.id=l.module_id JOIN programs p ON p.id=m.program_id ORDER BY p.id,m.order_no,l.order_no').all()));app.post('/api/admin/lessons',auth,admin,(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO lessons(module_id,title,type,content,video_url,file_url,order_no) VALUES(?,?,?,?,?,?,?)').run(Number(b.module_id),b.title,b.type||'Texte',b.content||'',b.video_url||'',b.file_url||'',Number(b.order_no||1));res.json({ok:true,id:r.lastInsertRowid})});
app.get('/api/admin/payments',auth,admin,(req,res)=>res.json(db.prepare('SELECT p.*,s.student_no,s.name student_name FROM payments p LEFT JOIN students s ON s.id=p.student_id ORDER BY p.id DESC').all()));app.post('/api/admin/payments',auth,admin,(req,res)=>{const b=req.body,ref=b.reference||`MAN-${Date.now()}`;try{const r=db.prepare('INSERT INTO payments(student_id,amount_htg,method,status,reference) VALUES(?,?,?,?,?)').run(Number(b.student_id),Number(b.amount_htg),b.method||'Manuel',b.status||'Confirmé',ref);res.json({ok:true,id:r.lastInsertRowid,reference:ref})}catch(e){res.status(400).json({error:e.message})}});
process.on('SIGTERM',()=>{try{db.close()}finally{process.exit(0)}});
process.on('SIGINT',()=>{try{db.close()}finally{process.exit(0)}});
app.listen(PORT,'0.0.0.0',()=>console.log(`CETEP FINAL running on ${PORT}`));
